create or replace PROCEDURE                       SP_PRINCIPAL_PRINCIPAL(P_USUARIO_EJECUTA IN VARCHAR2)
IS 
v_ACTIVAR_TRANSACCION NUMBER;
v_RAMDOM1 NUMBER;
v_RAMDOM2 NUMBER;
v_COUNT_FACTURA NUMBER;
v_COUNT_SALARIO NUMBER;
v_EXISTE NUMBER;
v_ID_ORDENES NUMBER;
BEGIN 

    SELECT ACTIVAR_TRANSACCION
        INTO v_ACTIVAR_TRANSACCION
        FROM G4_PROYECTO_USUARIO_4.GRUPO_4_CONTROL;

        WHILE v_ACTIVAR_TRANSACCION = 0 LOOP

            FOR I IN 1..10 LOOP

                FOR J IN 1..100 LOOP

                    SELECT ACTIVAR_TRANSACCION
                        INTO v_Activar_Transaccion
                        FROM G4_PROYECTO_USUARIO_4.GRUPO_4_CONTROL;

                END LOOP;

            END LOOP;

        END LOOP;

    SELECT COUNT(1)
        INTO v_COUNT_FACTURA
        FROM G4_PROYECTO_USUARIO_1.FACTURA;

     WHILE v_COUNT_FACTURA < 8 LOOP

          SELECT ROUND(DBMS_RANDOM.VALUE(1,10))
            INTO v_RAMDOM1
            FROM DUAL;

         SELECT COUNT(1)
           INTO v_EXISTE
            FROM G4_PROYECTO_USUARIO_3.ORDENES
            WHERE NUMERO_RANDOM = v_RAMDOM1;

        IF v_EXISTE = 0 THEN 
            G4_PROYECTO_USUARIO_4.FACTURA(v_RAMDOM1, P_USUARIO_EJECUTA);
        END IF;

        SELECT COUNT(1)
            INTO V_COUNT_FACTURA
            FROM G4_PROYECTO_USUARIO_1.FACTURA;


     END LOOP;

     SELECT COUNT(1)
        INTO v_COUNT_SALARIO
        FROM G4_PROYECTO_USUARIO_1.SALARIO;

        WHILE v_COUNT_SALARIO < 4 LOOP

            G4_PROYECTO_USUARIO_4.SALARIO;

            SELECT COUNT(1)
                INTO v_COUNT_SALARIO
                FROM G4_PROYECTO_USUARIO_1.SALARIO;

        END LOOP;
    
END;

DECLARE
  P_USUARIO_EJECUTA VARCHAR2(200);
BEGIN
  P_USUARIO_EJECUTA := 'Maikel';

  G4_PROYECTO_USUARIO_4.SP_PRINCIPAL_PRINCIPAL(
    P_USUARIO_EJECUTA => P_USUARIO_EJECUTA
  );
END;

GRANT EXECUTE ON  G4_PROYECTO_USUARIO_4.SP_PRINCIPAL_PRINCIPAL TO G4_PROYECTO_USUARIO_1;
GRANT EXECUTE ON  G4_PROYECTO_USUARIO_4.SP_PRINCIPAL_PRINCIPAL TO G4_PROYECTO_USUARIO_2;












































CREATE OR REPLACE PROCEDURE G4_PROYECTO_USUARIO_4.SP_PRINCIPAL_FACTURA (P_USUARIO_EJECUTA IN VARCHAR2)
IS
    v_ACTIVAR_TRANSACCION NUMBER;
    v_RAMDOM1 NUMBER;
    v_COUNT_FACTURA NUMBER;
    v_EXISTE NUMBER;
    CURSOR CUR_ATENDIDO
IS 
    SELECT  ORDE_ID, 
               ORDE_EMPLEADO_ID, 
               ORDE_CLIENTES_ID, 
               ORDE_MENU_ID, 
               ORDE_CANTIDAD
                FROM G4_PROYECTO_USUARIO_3.ORDENES
                WHERE ORDE_ATENDIDO = 0;

BEGIN

    SELECT ACTIVAR_TRANSACCION
        INTO v_ACTIVAR_TRANSACCION
        FROM G4_PROYECTO_USUARIO_4.GRUPO_4_CONTROL;

        WHILE v_ACTIVAR_TRANSACCION = 0 LOOP

            FOR I IN 1..10 LOOP

                FOR J IN 1..100 LOOP

                    SELECT ACTIVAR_TRANSACCION
                        INTO v_Activar_Transaccion
                        FROM G4_PROYECTO_USUARIO_4.GRUPO_4_CONTROL;

                END LOOP;

            END LOOP;

        END LOOP;

    SELECT COUNT(1)
        INTO v_COUNT_FACTURA
        FROM G4_PROYECTO_USUARIO_1.FACTURA;

    FOR principal IN CUR_ATENDIDO LOOP
    
    SELECT COUNT(1)
        INTO v_COUNT_FACTURA
        FROM G4_PROYECTO_USUARIO_1.FACTURA;
                
        WHILE v_COUNT_FACTURA < 8 LOOP

            SELECT ROUND(DBMS_RANDOM.VALUE(1,10))
                INTO v_RAMDOM1
                FROM DUAL;

            SELECT COUNT(1)
                INTO v_EXISTE
                FROM G4_PROYECTO_USUARIO_3.ORDENES
                WHERE NUMERO_RANDOM = v_RAMDOM1;
            
            IF v_EXISTE = 0 THEN
                G4_PROYECTO_USUARIO_4.SP_CREAR_FACTURA(principal.ORDE_EMPLEADO_ID,
                                                                                                principal.ORDE_CLIENTES_ID,
                                                                                                principal.ORDE_ID);

                G4_PROYECTO_USUARIO_4.SP_CREAR_DETALLE_FACTURA (G4_PROYECTO_USUARIO_4.FN_ID_FACTURA , principal.ORDE_MENU_ID,  principal.ORDE_CANTIDAD);

                G4_PROYECTO_USUARIO_4.SP_UPDATE_SUBTOTAL_FACUTURA (G4_PROYECTO_USUARIO_4.FN_ID_FACTURA);
                G4_PROYECTO_USUARIO_4.SP_UPDATE_TOTAL_FACUTURA (G4_PROYECTO_USUARIO_4.FN_ID_FACTURA);
                G4_PROYECTO_USUARIO_4.SP_UPDATE_ORDEN_ATENDIDA (principal.ORDE_ID); 

                UPDATE G4_PROYECTO_USUARIO_3.ORDENES
                    SET NUMERO_RANDOM = v_RAMDOM1, USUARIO_ATENDIO = P_USUARIO_EJECUTA
                    WHERE ORDE_ID = principal.ORDE_ID;
                COMMIT;
            END IF;
            
            SELECT COUNT(1)
                INTO v_COUNT_FACTURA
                FROM G4_PROYECTO_USUARIO_1.FACTURA;
                
        END LOOP;

    END LOOP;
END;


CREATE OR REPLACE PROCEDURE G4_PROYECTO_USUARIO_4.SP_PRINCIPAL_SALRIO
IS
    v_COUNT_SALARIO NUMBER;
    CURSOR CUR_SALARIO
IS
    SELECT  EMPL_ID
        FROM G4_PROYECTO_USUARIO_2.EMPLEADO
        WHERE EMPL_ID <=  G4_PROYECTO_USUARIO_4.FN_ID_EMPLEADO;
BEGIN

    FOR salario IN CUR_SALARIO LOOP
    
    SELECT COUNT(1)
        INTO v_COUNT_SALARIO
        FROM G4_PROYECTO_USUARIO_1.SALARIO;
        
         WHILE v_COUNT_SALARIO < 4 LOOP

        G4_PROYECTO_USUARIO_4.SP_PAGAR_SALARIO (salario.EMPL_ID);
        COMMIT;
        SELECT COUNT(1)
            INTO v_COUNT_SALARIO
            FROM G4_PROYECTO_USUARIO_1.SALARIO;
        
        END LOOP;
    END LOOP;
END;


CREATE OR REPLACE PROCEDURE G4_PROYECTO_USUARIO_4.SP_PRINCIPAL_PRUEBA (P_USUARIO_EJECUTA IN VARCHAR2)
IS
BEGIN 
    G4_PROYECTO_USUARIO_4.SP_PRINCIPAL_FACTURA (P_USUARIO_EJECUTA);
    G4_PROYECTO_USUARIO_4.SP_PRINCIPAL_SALRIO;
END;

DECLARE
  P_USUARIO_EJECUTA VARCHAR2(200);
BEGIN
  P_USUARIO_EJECUTA := 'Maikel';

  G4_PROYECTO_USUARIO_4.SP_PRINCIPAL_PRUEBA(
    P_USUARIO_EJECUTA => P_USUARIO_EJECUTA
  );

END;

GRANT EXECUTE ON G4_PROYECTO_USUARIO_4.SP_PRINCIPAL_PRUEBA TO G4_PROYECTO_USUARIO_1;
GRANT EXECUTE ON G4_PROYECTO_USUARIO_4.SP_PRINCIPAL_PRUEBA TO G4_PROYECTO_USUARIO_2;











