/*MAIKEL SOLAMENTE QUEDA DE EJECUTAR LOS INSERT Y MOSTRARLE AL PROFESOR QUE LAS TABLAS ESTÁN 
    VACIAS LUEGO MOSTRAR QUE EL CONTROL ESTE EN 0 ES DECIR APAGADO, IR A LA INSTANCIA DEL USUARIO 4 
    LUEGO A LA INSTANCIA DEL USUARIO 2 Y POR ÚLTIMO A LA INSTANCIA DEL USUARIO 1 Y EJECUTAR EN CADA UNA DE ESTAS EL PROCEDIMIENTO
    LUEGO VUELBES A LA INTANCIA DEL USUARIO 3 Y UPDATEAS LA TABLA CONTROL Y ENCIEDES LA CONCURRENCIA, DESPÚES DE ESTO 
    MUESTRAS LAS TABLAS CON EL ERROR QUE TENEMOS ACTUALMENTE,  SUERTE YO DEL FUTURO!
*/

UPDATE G4_PROYECTO_USUARIO_4.GRUPO_4_CONTROL 
    SET activar_transaccion = 1;
COMMIT;

UPDATE G4_PROYECTO_USUARIO_4.GRUPO_4_CONTROL 
    SET activar_transaccion = 0;
COMMIT;

SELECT * FROM G4_PROYECTO_USUARIO_4.GRUPO_4_CONTROL;
SELECT * FROM G4_PROYECTO_USUARIO_3.ORDENES;
SELECT * FROM G4_PROYECTO_USUARIO_1.SALARIO;

DELETE G4_PROYECTO_USUARIO_1.DETALLE_FACTURA;
DELETE G4_PROYECTO_USUARIO_1.FACTURA;
DELETE G4_PROYECTO_USUARIO_1.SALARIO;
DELETE G4_PROYECTO_USUARIO_3.ORDENES;
COMMIT;

/*INSERTAR DATOS EN LA TABLA ORDENES*/
--> LISTO
INSERT INTO G4_PROYECTO_USUARIO_3.ORDENES(ORDE_EMPLEADO_ID, ORDE_CLIENTES_ID, ORDE_MENU_ID, ORDE_CANTIDAD, ORDE_CALIFICACION,ORDE_ATENDIDO)
                                                                       VALUES (1, 1, 1, 10, -5, 0);
INSERT INTO G4_PROYECTO_USUARIO_3.ORDENES(ORDE_EMPLEADO_ID, ORDE_CLIENTES_ID, ORDE_MENU_ID, ORDE_CANTIDAD, ORDE_CALIFICACION,ORDE_ATENDIDO)
                                                                       VALUES (1, 2, 2, 3, -3, 0);
INSERT INTO G4_PROYECTO_USUARIO_3.ORDENES(ORDE_EMPLEADO_ID, ORDE_CLIENTES_ID, ORDE_MENU_ID, ORDE_CANTIDAD, ORDE_CALIFICACION,ORDE_ATENDIDO)
                                                                       VALUES (1, 3, 3, 5, -2, 0);    
INSERT INTO G4_PROYECTO_USUARIO_3.ORDENES(ORDE_EMPLEADO_ID, ORDE_CLIENTES_ID, ORDE_MENU_ID, ORDE_CANTIDAD, ORDE_CALIFICACION,ORDE_ATENDIDO)
                                                                       VALUES (2, 3, 3, 10, 2, 0);                                                                          
INSERT INTO G4_PROYECTO_USUARIO_3.ORDENES(ORDE_EMPLEADO_ID, ORDE_CLIENTES_ID, ORDE_MENU_ID, ORDE_CANTIDAD, ORDE_CALIFICACION,ORDE_ATENDIDO)
                                                                       VALUES (2, 1, 2, 10, 2, 0);                                                                        
INSERT INTO G4_PROYECTO_USUARIO_3.ORDENES(ORDE_EMPLEADO_ID, ORDE_CLIENTES_ID, ORDE_MENU_ID, ORDE_CANTIDAD, ORDE_CALIFICACION,ORDE_ATENDIDO)
                                                                       VALUES (2, 2, 1, 20, 2, 0);                                                                             
INSERT INTO G4_PROYECTO_USUARIO_3.ORDENES(ORDE_EMPLEADO_ID, ORDE_CLIENTES_ID, ORDE_MENU_ID, ORDE_CANTIDAD, ORDE_CALIFICACION,ORDE_ATENDIDO)
                                                                       VALUES (3, 2, 1, 1, -2, 0);                                                                          
INSERT INTO G4_PROYECTO_USUARIO_3.ORDENES(ORDE_EMPLEADO_ID, ORDE_CLIENTES_ID, ORDE_MENU_ID, ORDE_CANTIDAD, ORDE_CALIFICACION,ORDE_ATENDIDO)
                                                                       VALUES (3, 3, 1, 1, -1, 0);                                                                     
COMMIT; 


SELECT * FROM G4_PROYECTO_USUARIO_1.FACTURA;
SELECT * FROM G4_PROYECTO_USUARIO_1.DETALLE_FACTURA;
