CREATE TABLE G4_PROYECTO_USUARIO_1.FACTURA(
FACT_ID NUMBER,
FACT_FECHA DATE,
FACT_EMPLEADO_ID NUMBER,
FACT_CLIENTE_ID NUMBER,
FACT_SUBTOTAL NUMBER,
FACT_DESCUENTO NUMBER,
FACT_IVA NUMBER,
FACT_TOTAL NUMBER,
FACT_ORDENES_ID NUMBER,
CONSTRAINT PK_FACTURA PRIMARY KEY (FACT_ID), -- LLAVE PRIMARYA
CONSTRAINT FK_EMPLEADO_FACTURA FOREIGN KEY (FACT_EMPLEADO_ID)REFERENCES G4_PROYECTO_USUARIO_2.EMPLEADO(EMPL_ID),
CONSTRAINT FK_CLIENTE_FACTURA FOREIGN KEY (FACT_CLIENTE_ID)REFERENCES G4_PROYECTO_USUARIO_1.CLIENTES(CLIE_ID),
CONSTRAINT FK_ORDENES_FACTURA FOREIGN KEY (FACT_ORDENES_ID)REFERENCES G4_PROYECTO_USUARIO_3.ORDENES(ORDE_ID)
);

CREATE TABLE G4_PROYECTO_USUARIO_1.DETALLE_FACTURA(
DETA_ID NUMBER,
DETA_MENU_ID NUMBER,
DETA_FACTURA_ID NUMBER,
DETA_PRECIO NUMBER,
DETA_CANTIDAD NUMBER,
DETA_TOTAL NUMBER,
CONSTRAINT PK_DETALLE_FACTURA PRIMARY KEY (DETA_ID), -- LLAVE PRIMARYA
CONSTRAINT FK_DETALLE_FACTURA_FACTURA FOREIGN KEY (DETA_FACTURA_ID) REFERENCES G4_PROYECTO_USUARIO_1.FACTURA (FACT_ID),
CONSTRAINT FK_MENU_DETALLE_FACTURA FOREIGN KEY (DETA_MENU_ID)REFERENCES G4_PROYECTO_USUARIO_2.MENU(MENU_ID)
);

GRANT REFERENCES ON g4_proyecto_usuario_1.FACTURA TO G4_PROYECTO_USUARIO_1;

GRANT REFERENCES ON G4_PROYECTO_USUARIO_2.menu TO G4_PROYECTO_USUARIO_1;