/********** PASO #1 CREACIÓN DE LOS USUARIOS **********/

CREATE USER G4_PROYECTO_USUARIO_1 IDENTIFIED BY 
"ProyectoUser123" DEFAULT TABLESPACE DATA 
TEMPORARY TABLESPACE DATA 
QUOTA UNLIMITED ON DATA;

CREATE USER G4_PROYECTO_USUARIO_2 IDENTIFIED BY 
ProyectoUser123 DEFAULT TABLESPACE DATA 
TEMPORARY TABLESPACE DATA 
QUOTA UNLIMITED ON DATA;

CREATE USER G4_PROYECTO_USUARIO_3 IDENTIFIED BY 
ProyectoUser123 DEFAULT TABLESPACE DATA 
TEMPORARY TABLESPACE DATA 
QUOTA UNLIMITED ON DATA;

CREATE USER G4_PROYECTO_USUARIO_4 IDENTIFIED BY 
ProyectoUser123 DEFAULT TABLESPACE DATA 
TEMPORARY TABLESPACE DATA 
QUOTA UNLIMITED ON DATA;

/********** PASO #4 CREACIÓN DE LOS SCRIPS DE LAS TABLAS **********/
-- USUARIO 1

CREATE TABLE G4_PROYECTO_USUARIO_1.CLIENTES(
CLIE_ID number generated always as identity,
CLIE_NOMBRE varchar2(60)NOT NULL,
CLIE_CEDULA varchar2(25) NOT NULL UNIQUE,
CLIE_EMAIL varchar2(100)NOT NULL,
CLIE_TELEFONO varchar2(15),
CONSTRAINT PK_CLIENTES PRIMARY KEY (CLIE_ID) -- LLAVE PRIMARYA 
);

DROP TABLE G4_PROYECTO_USUARIO_1.FACTURA;
DROP TABLE G4_PROYECTO_USUARIO_1.DETALLE_FACTURA;

CREATE TABLE G4_PROYECTO_USUARIO_1.FACTURA(
FACT_ID NUMBER GENERATED ALWAYS AS IDENTITY,
FACT_FECHA DATE,
FACT_EMPLEADO_ID NUMBER,
FACT_CLIENTE_ID NUMBER,
FACT_SUBTOTAL NUMBER,
FACT_DESCUENTO NUMBER,
FACT_IVA NUMBER,
FACT_TOTAL NUMBER,
FACT_ORDENES_ID NUMBER,
CONSTRAINT PK_FACTURA PRIMARY KEY (FACT_ID), -- LLAVE PRIMARYA
CONSTRAINT FK_EMPLEADO_FACTURA FOREIGN KEY (FACT_EMPLEADO_ID)REFERENCES G4_PROYECTO_USUARIO_2.EMPLEADO(EMPL_ID),
CONSTRAINT FK_CLIENTE_FACTURA FOREIGN KEY (FACT_CLIENTE_ID)REFERENCES G4_PROYECTO_USUARIO_1.CLIENTES(CLIE_ID),
CONSTRAINT FK_ORDENES_FACTURA FOREIGN KEY (FACT_ORDENES_ID)REFERENCES G4_PROYECTO_USUARIO_3.ORDENES(ORDE_ID)
);

CREATE TABLE G4_PROYECTO_USUARIO_1.DETALLE_FACTURA(
DETA_ID NUMBER GENERATED ALWAYS AS IDENTITY,
DETA_MENU_ID NUMBER,
DETA_PRECIO NUMBER,
DETA_CANTIDAD NUMBER,
DETA_TOTAL NUMBER,
CONSTRAINT PK_DETALLE_FACTURA PRIMARY KEY (DETA_ID), -- LLAVE PRIMARYA
CONSTRAINT FK_DETALLE_FACTURA_FACTURA FOREIGN KEY (DETA_ID) REFERENCES G4_PROYECTO_USUARIO_1.FACTURA (FACT_ID),
CONSTRAINT FK_MENU_DETALLE_FACTURA FOREIGN KEY (DETA_MENU_ID)REFERENCES G4_PROYECTO_USUARIO_2.MENU(MENU_ID)
);

CREATE TABLE G4_PROYECTO_USUARIO_1.SALARIO(
SALA_ID NUMBER GENERATED ALWAYS AS IDENTITY,
SALA_FECHA DATE,
SALA_BONI_ID NUMBER,
SALA_REDU_ID NUMBER,
SALA_NETO NUMBER,
SALA_EMPLEADO_ID NUMBER,
CONSTRAINT PK_SALARIO PRIMARY KEY (SALA_ID,SALA_FECHA), -- LLAVE PRIMARYA
CONSTRAINT FK_BONIFICACION FOREIGN KEY (SALA_BONI_ID) REFERENCES G4_PROYECTO_USUARIO_3.BONIFICACION(BONI_ID),
CONSTRAINT FK_REDUCCION FOREIGN KEY (SALA_REDU_ID) REFERENCES G4_PROYECTO_USUARIO_3.REDUCCION(REDU_ID),
CONSTRAINT FK_EMPLEADO FOREIGN KEY (SALA_EMPLEADO_ID) REFERENCES G4_PROYECTO_USUARIO_2.EMPLEADO (EMPL_ID)
);

-- USUARIO 2 

CREATE TABLE G4_PROYECTO_USUARIO_2.EMPLEADO (
EMPL_ID NUMBER GENERATED ALWAYS AS IDENTITY,
EMPL_NOMBRE VARCHAR2(60) NOT NULL,
EMPL_CEDULA VARCHAR2(15) UNIQUE,
EMPL_TELEFONO VARCHAR2(15),
EMPL_DIRECCION VARCHAR2(150),
EMPL_EMAIL VARCHAR(50),
EMPL_CARGO_ID NUMBER(9),
CONSTRAINT PK_EMPLEADO PRIMARY KEY (EMPL_ID),
CONSTRAINT FK_EMPLEADO_CARGO_ID FOREIGN KEY (EMPL_CARGO_ID) REFERENCES G4_PROYECTO_USUARIO_2.CARGO(CARG_ID)
);

CREATE TABLE G4_PROYECTO_USUARIO_2.CARGO(
CARG_ID NUMBER GENERATED ALWAYS AS IDENTITY,
CARG_DESCRPCION VARCHAR2(60),
CARG_SALARIO_MINIMO NUMBER(9,2),
CONSTRAINT PK_CARGO PRIMARY KEY (CARG_ID)
);

CREATE TABLE G4_PROYECTO_USUARIO_2.MENU(
MENU_ID NUMBER GENERATED ALWAYS AS IDENTITY,
MENU_DESCRPCION VARCHAR2(60),
MENU_PRECIO NUMBER(9,2),
CONSTRAINT PK_MENU PRIMARY KEY (MENU_ID)
);

-- USUARIO 3

CREATE TABLE G4_PROYECTO_USUARIO_3.OREDENES(
ORDE_ID NUMBER GENERATED ALWAYS AS IDENTITY,
ORDE_EMPLEADO_ID NUMBER,
ORDE_CLIENTE_ID NUMBER,
ORDE_MENU_ID NUMBER,
ORDE_CANTIDAD NUMBER,
ORDE_CLASIFICACION,
CONSTRAINT PK_ORDENES PRIMARY KEY (ORDE_ID),
CONSTRAINT FK_EMPLEADO_ORDENES FOREIGN KEY (ORDE_EMPLEADO_ID) REFERENCES EMPLEADOS (EMPE_ID),
CONSTRAINT FK_CLIENTE_ORDENES FOREIGN KEY (ORDE_CLIENTE_ID) REFERENCES CLIENTE (CLIE_ID),
CONSTRAINT FK_MENU_ORDENES FOREIGN KEY (ORDE_MENU_ID) REFERENCES MENU (MENU_ID)
);

CREATE TABLE G4_PROYECTO_USUARIO_3.BONIFICACION(
BONI_ID NUMBER GENERATED ALWAYS AS IDENTITY,
BONI_DESCRIPCION VARCHAR (60),
BONI_PORCENTAJE NUMBER(9),
CONSTRAINT PK_BONIFICACION PRIMARY KEY (BONI_ID)
);


CREATE TABLE G4_PROYECTO_USUARIO_3.REDUCCION(
REDU_ID NUMBER GENERATED ALWAYS AS IDENTITY,
REDU_DESCRPCION VARCHAR (60),
REDU_PORCENTAJE NUMBER(9),
CONSTRAINT PK_REDUCCION PRIMARY KEY (REDU_ID)
);

/********** PASO #6 CREACIÓN DE LOS ROLES **********/

CREATE ROLE G4_CONEXION;
CREATE ROLE G4_DESARROLLADOR;
CREATE ROLE G4_LECTURA;

/********** PASO #7 AGREGAR LOS PERMISOS A LOS ROLES **********/

-- 1. PERMISOS PARA EL ROL G4_CONEXION
GRANT CREATE SESSION TO G4_CONEXION;

-- 2.1 PERMISOS PARA EL ROLE G4_DESARROLLADOR DE LAS TABLAS DEL USUARIO 1
-- PERMISO DE LEER.
GRANT SELECT ON G4_PROYECTO_USUARIO_1.CLIENTES TO G4_DESARROLLADOR;
GRANT SELECT ON G4_PROYECTO_USUARIO_1.FACTURA TO G4_DESARROLLADOR;
GRANT SELECT ON G4_PROYECTO_USUARIO_1.DETALLE_FACTURA TO G4_DESARROLLADOR;
GRANT SELECT ON G4_PROYECTO_USUARIO_1.SALARIO TO G4_DESARROLLADOR;

-- PERMISO DE INSERTAR.
GRANT INSERT ON G4_PROYECTO_USUARIO_1.CLIENTES TO G4_DESARROLLADOR;
GRANT INSERT ON G4_PROYECTO_USUARIO_1.FACTURA TO G4_DESARROLLADOR;
GRANT INSERT ON G4_PROYECTO_USUARIO_1.DETALLE_FACTURA TO G4_DESARROLLADOR;
GRANT INSERT ON G4_PROYECTO_USUARIO_1.SALARIO TO G4_DESARROLLADOR;

-- PERMISO DE ACTUALIZAR.
GRANT UPDATE ON G4_PROYECTO_USUARIO_1.CLIENTES TO G4_DESARROLLADOR;
GRANT UPDATE ON G4_PROYECTO_USUARIO_1.FACTURA TO G4_DESARROLLADOR;
GRANT UPDATE ON G4_PROYECTO_USUARIO_1.DETALLE_FACTURA TO G4_DESARROLLADOR;
GRANT UPDATE ON G4_PROYECTO_USUARIO_1.SALARIO TO G4_DESARROLLADOR;

-- PERMISO DE BORRAR.
GRANT DELETE ON G4_PROYECTO_USUARIO_1.CLIENTES TO G4_DESARROLLADOR;
GRANT DELETE ON G4_PROYECTO_USUARIO_1.FACTURA TO G4_DESARROLLADOR;
GRANT DELETE ON G4_PROYECTO_USUARIO_1.DETALLE_FACTURA TO G4_DESARROLLADOR;
GRANT DELETE ON G4_PROYECTO_USUARIO_1.SALARIO TO G4_DESARROLLADOR;

-- 2.2 PERMISOS PARA EL ROLE G4_DESARROLLADOR DE LAS TABLAS DEL USUARIO 2
-- PERMISO DE LEER.
GRANT SELECT ON G4_PROYECTO_USUARIO_2.EMPLEADO TO G4_DESARROLLADOR;
GRANT SELECT ON G4_PROYECTO_USUARIO_2.MENU TO G4_DESARROLLADOR;
GRANT SELECT ON G4_PROYECTO_USUARIO_2.CARGO TO G4_DESARROLLADOR;

-- PERMISOS PARA INSERTAR.
GRANT INSERT ON G4_PROYECTO_USUARIO_2.EMPLEADO TO G4_DESARROLLADOR;
GRANT INSERT ON G4_PROYECTO_USUARIO_2.MENU TO G4_DESARROLLADOR;
GRANT INSERT ON G4_PROYECTO_USUARIO_2.CARGO TO G4_DESARROLLADOR;

-- PERMISO PARA ACTUALIZAR.
GRANT UPDATE ON G4_PROYECTO_USUARIO_2.EMPLEADO TO G4_DESARROLLADOR;
GRANT UPDATE ON G4_PROYECTO_USUARIO_2.MENU TO G4_DESARROLLADOR;
GRANT UPDATE ON G4_PROYECTO_USUARIO_2.CARGO TO G4_DESARROLLADOR;

-- PERMISO PARA BORRAR.
GRANT DELETE ON G4_PROYECTO_USUARIO_2.EMPLEADO TO G4_DESARROLLADOR;
GRANT DELETE ON G4_PROYECTO_USUARIO_2.MENU TO G4_DESARROLLADOR;
GRANT DELETE ON G4_PROYECTO_USUARIO_2.CARGO TO G4_DESARROLLADOR;

-- 2.3 PERMISOS PARA EL ROLE G4_DESARROLLADOR DE LAS TABLAS DEL USUARIO 3
-- PERMISO DE LEER.
GRANT SELECT ON G4_PROYECTO_USUARIO_3.ORDENES TO G4_DESARROLLADOR;
GRANT SELECT ON G4_PROYECTO_USUARIO_3.BONIFICACION TO G4_DESARROLLADOR;
GRANT SELECT ON G4_PROYECTO_USUARIO_3.REDUCCION TO G4_DESARROLLADOR;

-- PERMISO PARA INSERTAR.
GRANT INSERT ON G4_PROYECTO_USUARIO_3.ORDENES TO G4_DESARROLLADOR;
GRANT INSERT ON G4_PROYECTO_USUARIO_3.BONIFICACION TO G4_DESARROLLADOR;
GRANT INSERT ON G4_PROYECTO_USUARIO_3.REDUCCION TO G4_DESARROLLADOR;

-- PERMISO PARA ACTUALIZAR.
GRANT UPDATE ON G4_PROYECTO_USUARIO_3.ORDENES TO G4_DESARROLLADOR;
GRANT UPDATE ON G4_PROYECTO_USUARIO_3.BONIFICACION TO G4_DESARROLLADOR;
GRANT UPDATE ON G4_PROYECTO_USUARIO_3.REDUCCION TO G4_DESARROLLADOR;

-- PERMISO PARA BORRAR.
GRANT DELETE ON G4_PROYECTO_USUARIO_3.ORDENES TO G4_DESARROLLADOR;
GRANT DELETE ON G4_PROYECTO_USUARIO_3.BONIFICACION TO G4_DESARROLLADOR;
GRANT DELETE ON G4_PROYECTO_USUARIO_3.REDUCCION TO G4_DESARROLLADOR;

-- PERMISO PARA CREAR TABLAS.
GRANT CREATE TABLE TO G4_DESARROLLADOR;

-- PERMISO PARA CREAR PROCEDIMIENTOS Y FUNCIONES.
GRANT CREATE PROCEDURE TO G4_DESARROLLADOR;

-- 3.1 PERMISOS PARA EL ROL G4_LECTURA DE LAS TABLAS DEL USUARIO 1

GRANT SELECT ON G4_PROYECTO_USUARIO_1.CLIENTES TO G4_LECTURA;
GRANT SELECT ON G4_PROYECTO_USUARIO_1.FACTURA TO G4_LECTURA;
GRANT SELECT ON G4_PROYECTO_USUARIO_1.DETALLE_FACTURA TO G4_LECTURA;
GRANT SELECT ON G4_PROYECTO_USUARIO_1.SALARIO TO G4_LECTURA; 

-- 3.2 PERMISOS PARA EL ROL G4_LECTURA DE LAS TABLAS DEL USUARIO 2

GRANT SELECT ON G4_PROYECTO_USUARIO_2.EMPLEADO TO G4_LECTURA;
GRANT SELECT ON G4_PROYECTO_USUARIO_2.MENU TO G4_LECTURA;
GRANT SELECT ON G4_PROYECTO_USUARIO_2.CARGO TO G4_LECTURA;

-- 3.3 PERMISOS PARA EL ROL G4_LECTURA DE LAS TABLAS DEL USUARIO 3

GRANT SELECT ON G4_PROYECTO_USUARIO_3.ORDENES TO G4_LECTURA;
GRANT SELECT ON G4_PROYECTO_USUARIO_3.BONIFICACION TO G4_LECTURA;
GRANT SELECT ON G4_PROYECTO_USUARIO_3.REDUCCION TO G4_LECTURA;

/********** PASO #8 ASIGNAR LOS ROLES A LOS USUARIOS **********/

-- USUARIO 1 (ROLE CONEXIÓN)

GRANT G4_CONEXION TO G4_PROYECTO_USUARIO_1;

-- USUARIO 2 (ROLE CONEXIÓN & ROLE LECTURA)

GRANT G4_CONEXION TO G4_PROYECTO_USUARIO_2;
GRANT G4_LECTURA TO G4_PROYECTO_USUARIO_2;

-- USUARIO 3 (ROLE CONEXÓN & ROLE DESARROLLADOR)

GRANT G4_CONEXION TO G4_PROYECTO_USUARIO_3;
GRANT G4_DESARROLLADOR TO G4_PROYECTO_USUARIO_3;

GRANT G4_CONEXION TO G4_PROYECTO_USUARIO_4;
GRANT G4_LECTURA TO G4_PROYECTO_USUARIO_4;
GRANT G4_DESARROLLADOR TO G4_PROYECTO_USUARIO_4;

/********** PASO #9 CONSULTAS **********/

-- PRIVILEGIOS DE SISTEMA DE LOS ROLES.
SELECT * FROM dba_sys_privs 
WHERE GRANTEE = 'G4_CONEXION';

SELECT * FROM dba_sys_privs 
WHERE GRANTEE = 'G4_DESARROLLADOR';

SELECT * FROM dba_sys_privs 
WHERE GRANTEE = 'G4_LECTURA';

-- PRIVILEGIOS DE OBJETOS DE LOS ROLES.

SELECT * FROM dba_tab_privs
WHERE GRANTEE = 'G4_CONEXION';

SELECT * FROM dba_tab_privs 
WHERE GRANTEE = 'G4_DESARROLLADOR';

SELECT * FROM dba_tab_privs 
WHERE GRANTEE = 'G4_LECTURA';

-- ROLES ASIGNADOS A LOS USUARIOS

select grantee, granted_role from dba_role_privs
  where grantee = upper ('G4_PROYECTO_USUARIO_1');

select grantee, granted_role from dba_role_privs
  where grantee = upper ('G4_PROYECTO_USUARIO_2');

select grantee, granted_role from dba_role_privs
  where grantee = upper ('G4_PROYECTO_USUARIO_3');

-- SCRIPS DE CONFIRMACION DE LOS ROLES 

-- usuario 3
INSERT INTO G4_PROYECTO_USUARIO_1.CLIENTES (CLIE_NOMBRE, clie_cedula, clie_email, clie_telefono) 
                        VALUES('Hernadez', '304350123', 'hernadez@gmail.com', '87651234');
COMMIT;

INSERT INTO G4_PROYECTO_USUARIO_1.SALARIO (CLIE_NOMBRE, clie_cedula, clie_email, clie_telefono) 
                        VALUES('Hernadez', '304350123', 'hernadez@gmail.com', '87651234');
COMMIT;

-- usuario 3
select * from G4_PROYECTO_USUARIO_2.MENU;

-- USUARIO 3
UPDATE G4_PROYECTO_USUARIO_1.CLIENTES 
SET CLIE_NOMBRE = 'Jorge'
WHERE CLIE_ID = 2;

-- USUARIO 3 
DELETE G4_PROYECTO_USUARIO_1.CLIENTES
WHERE CLIE_ID = 2;

-- USUARIO 2
SELECT * FROM G4_PROYECTO_USUARIO_1.CLIENTES;