/**************************************************** CREACIÓN DE LA FACTURA ****************************************************/

/*
 * PROCEDIMIENTO QUE CREA LA FACTURA 
 */
CREATE OR REPLACE PROCEDURE G4_PROYECTO_USUARIO_4.SP_GENERAR_FACTURA(
                                                                     PID_EMPLEADO IN NUMBER,
                                                                     PID_CLIENTE IN NUMBER,
                                                                     PID_ORDENES IN NUMBER,
                                                                     PID_MENU IN NUMBER,
                                                                     PCANTIDAD IN NUMBER)
IS 
v_CONSECUTIVO_FACRURA NUMBER;
BEGIN
    INSERT INTO G4_PROYECTO_USUARIO_1.FACTURA (FACT_ID, FACT_FECHA, FACT_EMPLEADO_ID, FACT_CLIENTE_ID, FACT_DESCUENTO, FACT_IVA, FACT_ORDENES_ID)
                                                                          VALUES (G4_PROYECTO_USUARIO_4.FN_CONTADOR_ID_FACTURA,
                                                                                          SYSDATE, PID_EMPLEADO, PID_CLIENTE, 0, 0.13, PID_ORDENES);
     COMMIT;                                                                    
   
 G4_PROYECTO_USUARIO_4.SP_GENERAR_DETALLE_FACTURA (G4_PROYECTO_USUARIO_4.FN_CONTADOR_ID_DETALLE_FACTURA, G4_PROYECTO_USUARIO_4.FN_CONSECUTIVO_FACTURA , PID_MENU,PCANTIDAD);
 G4_PROYECTO_USUARIO_4.SP_MODIFICA_SUBTOTAL_FACUTURA;
 G4_PROYECTO_USUARIO_4.SP_MODIFICA_TOTAL_FACUTURA;
END;

--> PRUEBA DEL PROCEDIMIENTO.
EXECUTE G4_PROYECTO_USUARIO_4.SP_GENERAR_FACTURA(1,1,1,1,10);  
EXECUTE G4_PROYECTO_USUARIO_4.SP_GENERAR_FACTURA(2, 2, 2, 0, 0.13, 4, 2, 3, 10, 2);  
EXECUTE G4_PROYECTO_USUARIO_4.SP_GENERAR_FACTURA(3, 3, 2, 0, 0.13, 7, 3, 1, 1, 3);

EXECUTE G4_PROYECTO_USUARIO_4.SP_GENERAR_FACTURA(0, 4, 0, 0, 0, 0, 0, 0, 0, 4);  

SELECT * FROM G4_PROYECTO_USUARIO_1.FACTURA;
SELECT * FROM G4_PROYECTO_USUARIO_1.DETALLE_FACTURA;
SELECT * FROM G4_PROYECTO_USUARIO_1.SALARIO;
SELECT * FROM G4_PROYECTO_USUARIO_3.ORDENES;
SELECT * FROM G4_PROYECTO_USUARIO_2.EMPLEADO;

DELETE G4_PROYECTO_USUARIO_1.DETALLE_FACTURA;
DELETE G4_PROYECTO_USUARIO_1.FACTURA;
DELETE G4_PROYECTO_USUARIO_1.SALARIO;
DELETE G4_PROYECTO_USUARIO_3.ORDENES;
COMMIT;

/*
 * FUNCIÓN QUE OBTINE EL ID MÁXIMO DE LA TABLA FACTURAS.
 por si en lagun momento se pierde la conexion  se sabe que se está trabajando al ultimo
 */
CREATE OR REPLACE FUNCTION  G4_PROYECTO_USUARIO_4.FN_CONSECUTIVO_FACTURA 
RETURN NUMBER 
IS 
v_CONSECUTIVO_MAXIMO NUMBER;
BEGIN 
    SELECT MAX (FACT_ID)
        INTO v_CONSECUTIVO_MAXIMO
            FROM  G4_PROYECTO_USUARIO_1.FACTURA;
            
RETURN v_CONSECUTIVO_MAXIMO;
END;
--> PRUEBA DE LA FUNCIÓN.
SELECT G4_PROYECTO_USUARIO_4.FN_CONSECUTIVO_FACTURA
 FROM DUAL;
 
 /*
 * PROCEDIMIENTO QUE GENERA EL DETALLE DE FACTURA.
 aqui se utilizan don funciones
 G4_PROYECTO_USUARIO_4.FN_GET_PRECIO_PLATILLO (PID_MENU) --> precio del platillo
 G4_PROYECTO_USUARIO_4.FN_MONTO_TOTAL_DETALLE (PCANTIDAD, PID_MENU) )--> total del detalle de la factura cantidad*precio del platillo() y re
 */
CREATE OR REPLACE PROCEDURE G4_PROYECTO_USUARIO_4.SP_GENERAR_DETALLE_FACTURA (PID_DETALLE_FACTURA IN NUMBER,
                                                                              PID_FACTURA IN NUMBER,
                                                                              PID_MENU IN NUMBER,
                                                                              PCANTIDAD IN NUMBER
                                                                              )
IS 
v_CONSECUTIVO_DETALLE_FACRURA NUMBER;
BEGIN 
    INSERT INTO G4_PROYECTO_USUARIO_1.detalle_factura (DETA_ID, DETA_FACTURA_ID, DETA_MENU_ID, DETA_CANTIDAD, DETA_PRECIO, DETA_TOTAL)
                                                                              VALUES (PID_DETALLE_FACTURA, PID_FACTURA,PID_MENU,  PCANTIDAD,  G4_PROYECTO_USUARIO_4.FN_GET_PRECIO_PLATILLO (PID_MENU), 
                                                                                             G4_PROYECTO_USUARIO_4.FN_MONTO_TOTAL_DETALLE (PCANTIDAD, PID_MENU) );
     COMMIT;
     
    v_CONSECUTIVO_DETALLE_FACRURA := G4_PROYECTO_USUARIO_4.FN_CONSECUTIVO_DETALLE_FACTURA;  
END;
--> PRUEBA DEL PROCEDIMIENTO.
EXECUTE G4_PROYECTO_USUARIO_4.SP_GENERAR_DETALLE_FACTURA (2, 2, 2, 3);
SELECT * FROM g4_proyecto_usuario_1.DETALLE_FACTURA;
 /*
 * FUNCIÓN QUE OBTINE EL ID MÁXIMO DE LA TABLA DETALLE_FACTURAS.
 */
CREATE OR REPLACE FUNCTION  G4_PROYECTO_USUARIO_4.FN_CONSECUTIVO_DETALLE_FACTURA 
RETURN NUMBER 
IS 
v_CONSECUTIVO_MAXIMO NUMBER;
BEGIN 
    SELECT MAX (DETA_ID)
        INTO v_CONSECUTIVO_MAXIMO
            FROM  G4_PROYECTO_USUARIO_1.DETALLE_FACTURA;
            
RETURN v_CONSECUTIVO_MAXIMO;
END;
--> PRUEBA DE LA FUNCIÓN.
SELECT G4_PROYECTO_USUARIO_4.FN_CONSECUTIVO_DETALLE_FACTURA
 FROM DUAL;

/*
 * FUNCIÓN QUE ME RETORNA EL PRECIO DE DEL PLATILLO.
 */
CREATE OR REPLACE FUNCTION G4_PROYECTO_USUARIO_4.FN_GET_PRECIO_PLATILLO (PID_MENU IN NUMBER)
RETURN NUMBER
IS 
V_PRECIO NUMBER;
BEGIN
    SELECT MENU_PRECIO
        INTO V_PRECIO
            FROM G4_PROYECTO_USUARIO_2.MENU
                WHERE MENU_ID = PID_MENU;
    RETURN V_PRECIO;
END;
--> PRUEBA DE LA FUNCIÓN.
SELECT G4_PROYECTO_USUARIO_4.FN_GET_PRECIO_PLATILLO(2)
 FROM DUAL;

/*
 * FUNCIÓN CALCULA EL MONTO TOTAL DEL DETALLE FACTURA.
 */
 CREATE OR REPLACE FUNCTION G4_PROYECTO_USUARIO_4.FN_MONTO_TOTAL_DETALLE (PCANTIDAD IN NUMBER, PMENU_ID IN NUMBER)
RETURN NUMBER
IS 
v_MONTO_TOTAL NUMBER;
BEGIN 
    v_MONTO_TOTAL := PCANTIDAD * G4_PROYECTO_USUARIO_4.FN_GET_PRECIO_PLATILLO (PMENU_ID);
    
RETURN v_MONTO_TOTAL;

END;
--> PRUEBA DE LA FUNCIÓN.
SELECT G4_PROYECTO_USUARIO_4.FN_MONTO_TOTAL_DETALLE (3, 2)
 FROM DUAL;

/*
 * FUNCIÓN QUE CALCULA EL SUBTOTAL DE LA FACTURA.
 */
CREATE OR REPLACE FUNCTION G4_PROYECTO_USUARIO_4.FN_CALCULAR_SUBTOTAL 
RETURN NUMBER
IS
v_CONSECUTIVO_MAXIMO NUMBER;
v_SUBTOTAL NUMBER;
BEGIN 
   
   SELECT MAX (FACT_ID)
        INTO v_CONSECUTIVO_MAXIMO
            FROM  G4_PROYECTO_USUARIO_1.FACTURA;
   
   SELECT SUM (DETA_TOTAL)
        INTO v_SUBTOTAL
            FROM G4_PROYECTO_USUARIO_1.DETALLE_FACTURA
                WHERE DETA_ID = v_CONSECUTIVO_MAXIMO;
                                
RETURN v_SUBTOTAL;
END;
--> PRUEBA DE LA FUNCIÓN.
SELECT G4_PROYECTO_USUARIO_4.FN_CALCULAR_SUBTOTAL
 FROM DUAL;

/*
 * FUNCIÓN QUE CALCULA EL MONTO TOTAL DE LA FACTURA.
 */
CREATE OR REPLACE FUNCTION G4_PROYECTO_USUARIO_4.FN_TOTAL_FACTURA (p_DESCUENTO IN NUMBER, 
                                                                   p_IVA IN NUMBER)
RETURN NUMBER
IS 
v_TOTAL NUMBER;
v_IVA_CALC NUMBER;
BEGIN 

    v_IVA_CALC := (G4_PROYECTO_USUARIO_4.FN_CALCULAR_SUBTOTAL * p_IVA);
    v_TOTAL :=  G4_PROYECTO_USUARIO_4.FN_CALCULAR_SUBTOTAL + v_IVA_CALC - p_DESCUENTO;
    
RETURN v_TOTAL;
END;
--> PRUEBA DE LA FUNCIÓN.
SELECT G4_PROYECTO_USUARIO_4.FN_TOTAL_FACTURA (0, 0.13)
 FROM DUAL;

 /*
 * PROCEDIMIENTO QUE MODIFICA EL SUBTOTAL DE LA FACTURA.
 */
CREATE OR REPLACE PROCEDURE G4_PROYECTO_USUARIO_4.SP_MODIFICA_SUBTOTAL_FACUTURA 
IS 
v_MAX_ID NUMBER;
BEGIN
SELECT MAX (FACT_ID) INTO v_MAX_ID FROM  G4_PROYECTO_USUARIO_1.FACTURA;

    UPDATE G4_PROYECTO_USUARIO_1.FACTURA
        SET FACT_SUBTOTAL = G4_PROYECTO_USUARIO_4.FN_CALCULAR_SUBTOTAL
            WHERE FACT_ID = v_MAX_ID;
    COMMIT;
END;
--> PRUEBA DEL PROCEDIMIENTO.
EXECUTE G4_PROYECTO_USUARIO_4.SP_MODIFICA_SUBTOTAL_FACUTURA;
SELECT * FROM G4_PROYECTO_USUARIO_1.FACTURA;
 /*
 * PROCEDIMIENTO QUE MODIFICA EL TOTAL DE LA FACTURA.
 */
CREATE OR REPLACE PROCEDURE G4_PROYECTO_USUARIO_4.SP_MODIFICA_TOTAL_FACUTURA (p_DESCUENTO IN NUMBER, 
                                                                              p_IVA IN NUMBER)
IS 
v_MAX_ID NUMBER;
BEGIN
SELECT MAX (FACT_ID) INTO v_MAX_ID FROM  G4_PROYECTO_USUARIO_1.FACTURA;

    UPDATE G4_PROYECTO_USUARIO_1.FACTURA
        SET FACT_TOTAL = G4_PROYECTO_USUARIO_4.FN_TOTAL_FACTURA (p_DESCUENTO, p_IVA)
            WHERE FACT_ID = v_MAX_ID;
     COMMIT;       
END;
--> PRUEBA DEL PROCEDIMIENTO.
EXECUTE G4_PROYECTO_USUARIO_4.SP_MODIFICA_TOTAL_FACUTURA (0, 0.13);

 /*
 * PROCEDIMIENTO QUE MODIFICA EL CAMPO ORDE ATENDIDA DE LA TABLA ORDENES MEDIANTE UN CURSOR.
 */
CREATE OR REPLACE PROCEDURE G4_PROYECTO_USUARIO_4.MODIFICAR_ORDEN_ATENDIDA_CURSOR (P_EMPLEADO_ID IN NUMBER)
IS
CURSOR CUR_ATENDIDO
IS 
SELECT ORDE_ATENDIDO 
    FROM G4_PROYECTO_USUARIO_3.ORDENES;
BEGIN

    FOR v_REG IN CUR_ATENDIDO LOOP
           G4_PROYECTO_USUARIO_4.SP_MODIFICAR_ORDE_ATENDIDO (P_EMPLEADO_ID);
    END LOOP;
END;
EXECUTE G4_PROYECTO_USUARIO_4.MODIFICAR_ORDEN_ATENDIDA_CURSOR (3);
SELECT * FROM G4_PROYECTO_USUARIO_3.ORDENES;
 /*
 * PROCEDIMIENTO QUE MODIFICA EL CAMPO ORDE ATENDIDA DE LA TABLA ORDENES.
 */
CREATE OR REPLACE PROCEDURE G4_PROYECTO_USUARIO_4.SP_MODIFICAR_ORDE_ATENDIDO (P_ORDE_ID IN NUMBER)
IS
BEGIN 

    UPDATE G4_PROYECTO_USUARIO_3.ORDENES
        SET ORDENES.ORDE_ATENDIDO = 1
            WHERE ORDE_EMPLEADO_ID = P_ORDE_ID;
    COMMIT;
END;
EXECUTE G4_PROYECTO_USUARIO_4.SP_MODIFICAR_ORDE_ATENDIDO (1);